=== ShowEQ/ShowEQ/showeq/tags/v5_0_0_25/conf/seqopcodes.dtd
<!ELEMENT seqopcodes (opcode)* >
<!ATTLIST seqopcodes 
 version CDATA #IMPLIED>

<!ELEMENT opcode (comment|payload)* >
<!ATTLIST opcode 
  id CDATA #REQUIRED
  name CDATA ""
  updated CDATA "">

<!ELEMENT comment (#PCDATA)>

<!ELEMENT payload EMPTY>
<!ATTLIST payload 
  dir CDATA "both"
  typename CDATA ""
  sizechecktype CDATA "none">

=== ShowEQ/ShowEQ/showeq/tags/v5_12_3_0/conf/worldopcodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seqopcodes SYSTEM "seqopcodes.dtd">
<seqopcodes>
    <!-- OLD OPCODES - these need updating still post 1/26/2005 

    <opcode id="02a5" name="OP_UserCompInfo" updated="02/10/04">
        <comment>User submitted computer information</comment>
    </opcode>
    <opcode id="02db" name="OP_LoginComplete" updated="02/10/04">
        <comment></comment>
    </opcode>
-->

    <opcode id="5B0B" name="OP_GuildList" updated="01/17/08">
        <comment>old GuildListCode</comment>
        <payload dir="server" typename="worldGuildListStruct" sizechecktype="match"/>
    </opcode>
    <opcode id="192E" name="OP_MOTD" updated="01/17/08">
        <comment>old MOTDCode Server message of the day</comment>
        <payload dir="server" typename="worldMOTDStruct" sizechecktype="none"/>
    </opcode>

<!-- Not necessary for SEQ to run but here to name packets in logs -->
    <opcode id="4892" name="OP_SendLoginInfo" updated="01/17/08">
        <comment>Client starting world session by asking for login information</comment>
    </opcode>

    <opcode id="4762" name="OP_LogServer" updated="01/17/08">
        <comment></comment>
    </opcode>
    <opcode id="701F" name="OP_ApproveWorld" updated="01/17/08">
        <comment></comment>
    </opcode>
    <opcode id="399F" name="OP_EnterWorld" updated="01/17/08">
        <comment>Server approval for client to enter world</comment>
    </opcode>
    <opcode id="7519" name="OP_ExpansionInfo" updated="01/17/08">
        <comment>Which expansions user has</comment>
    </opcode>
    <opcode id="0F14" name="OP_SendCharInfo" updated="01/17/08">
        <comment>Send all chars visible @ char select</comment>
    </opcode>
    <opcode id="0CA5" name="OP_SendSpellChecksum" updated="01/17/08">
        <comment>Contains a snippet of spell data</comment>
    </opcode>
    <opcode id="1CB3" name="OP_SendExeChecksum" updated="01/17/08">
        <comment>Second client verification packet</comment>
    </opcode>
    <opcode id="679D" name="OP_SendBaseDataChecksum" updated="01/17/08">
	    <comment>Second client verification packet</comment>
    </opcode>
    <opcode id="21C7" name="OP_SendSkillCapsChecksum" updated="01/17/08">
        <comment>Third client verification packet</comment>
    </opcode>
    <opcode id="26C4" name="OP_SetChatServer" updated="01/17/08">
        <comment>Chatserver? IP,Port,servername.Charname,password(?)</comment>
    </opcode>
    <opcode id="1C20" name="OP_SetChatServer2" updated="01/17/08">
        <comment>Chatserver? IP,Port,servername.Charname,password(?)</comment>
    </opcode>
    <opcode id="13DA" name="OP_ZoneServerInfo" updated="01/17/08">
        <comment>old ZoneServerInfo</comment>
    </opcode>
    <opcode id="3331" name="OP_WorldComplete" updated="01/17/08">
        <comment>Client telling world server it is done. World replies by disconnecting.</comment>
    </opcode>
    <opcode id="0254" name="OP_DeleteCharacter" updated="01/17/08">
        <comment>Delete character @ char select</comment>
    </opcode>
    <opcode id="1513" name="OP_CharacterCreate" updated="01/17/08">
        <comment>Create character @ char select</comment>
    </opcode>
    <opcode id="413F" name="OP_ApproveName" updated="01/17/08">
        <comment>Approving new character name @ char creation</comment>
    </opcode>
    <opcode id="4849" name="OP_RandomNameGenerator" updated="01/17/08">
        <comment>Returns a random name</comment>
    </opcode>

</seqopcodes>

=== ShowEQ/ShowEQ/showeq/tags/v5_0_0_17/conf/worldopcodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seqopcodes SYSTEM "seqopcodes.dtd">
<seqopcodes>
    <!-- OLD OPCODES - these need updating still post 1/26/2005 


    <opcode id="0018" name="OP_AckPacket" updated="02/10/04">
        <comment>Appears to be generic ack at the presentation level</comment>
    </opcode>
    <opcode id="00e3" name="OP_ExpansionInfo" updated="02/10/04">
        <comment>Which expansions user has</comment>
    </opcode>
    <opcode id="00ec" name="OP_DeleteCharacter" updated="02/10/04">
        <comment>Delete character @ char select</comment>
    </opcode>
    <opcode id="0106" name="OP_CharacterCreate" updated="02/10/04">
        <comment>Create character @ char select</comment>
    </opcode>
    <opcode id="0127" name="OP_ApproveName" updated="02/10/04">
        <comment>Approving new character name @ char creation</comment>
    </opcode>
    <opcode id="015a" name="OP_World_Client_CRC1" updated="07/14/04">
        <comment>Contains a snippet of spell data</comment>
    </opcode>
    <opcode id="0160" name="OP_World_Client_CRC2" updated="02/10/04">
        <comment>Second client verification packet</comment>
    </opcode>
    <opcode id="0188" name="OP_LogServer" updated="02/10/04">
        <comment></comment>
    </opcode>
    <opcode id="0196" name="OP_ApproveWorld" updated="02/10/04">
        <comment></comment>
    </opcode>
    <opcode id="0241" name="OP_SendLoginInfo" updated="02/10/04">
        <comment></comment>
    </opcode>
    <opcode id="0264" name="OP_EnterWorld" updated="02/10/04">
        <comment>Server approval for client to enter world</comment>
    </opcode>
    <opcode id="02a5" name="OP_UserCompInfo" updated="02/10/04">
        <comment>User submitted computer information</comment>
    </opcode>
    <opcode id="02ae" name="OP_GetName" updated="02/10/04">
        <comment>Returns a random name</comment>
    </opcode>
    <opcode id="02db" name="OP_LoginComplete" updated="02/10/04">
        <comment></comment>
    </opcode>
-->




    <opcode id="1560" name="OP_ZoneServerInfo" updated="01/26/05">
        <comment>old ZoneServerInfo</comment>
    </opcode>
    <opcode id="2628" name="OP_SendCharInfo" updated="01/26/05">
        <comment>Send all chars visible @ char select</comment>
    </opcode>
    <opcode id="4b97" name="OP_MOTD" updated="01/26/05">
        <comment>old MOTDCode Server message of the day</comment>
        <payload dir="server" typename="worldMOTDStruct" sizechecktype="none"/>
    </opcode>
    <opcode id="5dd9" name="OP_GuildList" updated="01/26/05">
        <comment>old GuildListCode</comment>
        <payload dir="server" typename="worldGuildListStruct" sizechecktype="match"/>
    </opcode>
    <opcode id="7e66" name="OP_SetChatServer" updated="01/26/05">
        <comment>Chatserver? IP,Port,servername.Charname,password(?)</comment>
    </opcode>
</seqopcodes>

=== ShowEQ/ShowEQ/showeq/tags/v5_0_0_24/conf/worldopcodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seqopcodes SYSTEM "seqopcodes.dtd">
<seqopcodes>
    <!-- OLD OPCODES - these need updating still post 1/26/2005 

    <opcode id="02a5" name="OP_UserCompInfo" updated="02/10/04">
        <comment>User submitted computer information</comment>
    </opcode>
    <opcode id="02db" name="OP_LoginComplete" updated="02/10/04">
        <comment></comment>
    </opcode>
-->


    <opcode id="407c" name="OP_ZoneServerInfo" updated="06/29/05">
        <comment>old ZoneServerInfo</comment>
    </opcode>
    <opcode id="732c" name="OP_SendCharInfo" updated="06/29/05">
        <comment>Send all chars visible @ char select</comment>
    </opcode>
    <opcode id="7fea" name="OP_MOTD" updated="06/29/05">
        <comment>old MOTDCode Server message of the day</comment>
        <payload dir="server" typename="worldMOTDStruct" sizechecktype="none"/>
    </opcode>
    <opcode id="6957" name="OP_GuildList" updated="06/29/05">
        <comment>old GuildListCode</comment>
        <payload dir="server" typename="worldGuildListStruct" sizechecktype="match"/>
    </opcode>
    <opcode id="6238" name="OP_SetChatServer" updated="06/29/05">
        <comment>Chatserver? IP,Port,servername.Charname,password(?)</comment>
    </opcode>
    <opcode id="6536" name="OP_SetChatServer2" updated="06/29/05">
        <comment>Chatserver? IP,Port,servername.Charname,password(?)</comment>
    </opcode>
    <opcode id="41b1" name="OP_ApproveWorld" updated="06/29/05">
        <comment></comment>
    </opcode>
    <opcode id="4668" name="OP_LogServer" updated="06/29/05">
        <comment></comment>
    </opcode>
    <opcode id="2792" name="OP_SendLoginInfo" updated="06/29/05">
        <comment>Client starting world session by asking for login information</comment>
    </opcode>
    <opcode id="509d" name="OP_WorldComplete" updated="06/29/05">
        <comment>Client telling world server it is done. World replies by disconnecting.</comment>
    </opcode>
    <opcode id="254d" name="OP_World_Client_CRC1" updated="06/29/05">
        <comment>Contains a snippet of spell data</comment>
    </opcode>
    <opcode id="16c9" name="OP_World_Client_CRC2" updated="06/29/05">
        <comment>Second client verification packet</comment>
    </opcode>
    <opcode id="5c78" name="OP_ExpansionInfo" updated="06/29/05">
        <comment>Which expansions user has</comment>
    </opcode>
    <opcode id="7262" name="OP_EnterWorld" updated="06/29/05">
        <comment>Server approval for client to enter world</comment>
    </opcode>
    <opcode id="0920" name="OP_DeleteCharacter" updated="06/29/05">
        <comment>Delete character @ char select</comment>
    </opcode>
    <opcode id="6160" name="OP_CharacterCreate" updated="06/29/04">
        <comment>Create character @ char select</comment>
    </opcode>
    <opcode id="46b1" name="OP_ApproveName" updated="06/29/04">
        <comment>Approving new character name @ char creation</comment>
    </opcode>
    <opcode id="23d4" name="OP_RandomNameGenerator" updated="06/29/05">
        <comment>Returns a random name</comment>
    </opcode>
</seqopcodes>

=== ShowEQ/ShowEQ/conf/worldopcodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seqopcodes SYSTEM "seqopcodes.dtd">
<seqopcodes>
    <!-- OLD OPCODES - these need updating still post 1/26/2005 

    <opcode id="02a5" name="OP_UserCompInfo" updated="02/10/04">
        <comment>User submitted computer information</comment>
    </opcode>
    <opcode id="02db" name="OP_LoginComplete" updated="02/10/04">
        <comment></comment>
    </opcode>
-->


    <opcode id="032f" name="OP_SendLoginInfo" updated="04/19/06">
        <comment>Client starting world session by asking for login information</comment>
    </opcode>
    <opcode id="4591" name="OP_GuildList" updated="04/19/06">
        <comment>old GuildListCode</comment>
        <payload dir="server" typename="worldGuildListStruct" sizechecktype="match"/>
    </opcode>
    <opcode id="6b98" name="OP_LogServer" updated="04/19/06">
        <comment></comment>
    </opcode>
    <opcode id="49da" name="OP_ApproveWorld" updated="04/19/06">
        <comment></comment>
    </opcode>
    <opcode id="6f38" name="OP_EnterWorld" updated="04/19/06">
        <comment>Server approval for client to enter world</comment>
    </opcode>
    <opcode id="7af3" name="OP_ExpansionInfo" updated="04/19/06">
        <comment>Which expansions user has</comment>
    </opcode>
    <opcode id="1393" name="OP_SendCharInfo" updated="04/19/06">
        <comment>Send all chars visible @ char select</comment>
    </opcode>
    <opcode id="4913" name="OP_World_Client_CRC1" updated="04/19/06">
        <comment>Contains a snippet of spell data</comment>
    </opcode>
    <opcode id="2710" name="OP_World_Client_CRC2" updated="04/19/06">
        <comment>Second client verification packet</comment>
    </opcode>
    <opcode id="7ec2" name="OP_MOTD" updated="04/19/06">
        <comment>old MOTDCode Server message of the day</comment>
        <payload dir="server" typename="worldMOTDStruct" sizechecktype="none"/>
    </opcode>
    <opcode id="13b1" name="OP_SetChatServer" updated="04/19/06">
        <comment>Chatserver? IP,Port,servername.Charname,password(?)</comment>
    </opcode>
    <opcode id="531f" name="OP_SetChatServer2" updated="04/19/06">
        <comment>Chatserver? IP,Port,servername.Charname,password(?)</comment>
    </opcode>
    <opcode id="654c" name="OP_ZoneServerInfo" updated="04/19/06">
        <comment>old ZoneServerInfo</comment>
    </opcode>
    <opcode id="032b" name="OP_WorldComplete" updated="04/19/06">
        <comment>Client telling world server it is done. World replies by disconnecting.</comment>
    </opcode>


    

    <opcode id="26c9" name="OP_DeleteCharacter" updated="10/27/05">
        <comment>Delete character @ char select</comment>
    </opcode>
    <opcode id="6160" name="OP_CharacterCreate" updated="06/29/04">
        <comment>Create character @ char select</comment>
    </opcode>
    <opcode id="3ea6" name="OP_ApproveName" updated="10/27/04">
        <comment>Approving new character name @ char creation</comment>
    </opcode>
    <opcode id="23d4" name="OP_RandomNameGenerator" updated="06/29/05">
        <comment>Returns a random name</comment>
    </opcode>
</seqopcodes>

=== ShowEQ/ShowEQ/showeq/tags/v5_3_0_0/conf/worldopcodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seqopcodes SYSTEM "seqopcodes.dtd">
<seqopcodes>
    <!-- OLD OPCODES - these need updating still post 1/26/2005 

    <opcode id="02a5" name="OP_UserCompInfo" updated="02/10/04">
        <comment>User submitted computer information</comment>
    </opcode>
    <opcode id="02db" name="OP_LoginComplete" updated="02/10/04">
        <comment></comment>
    </opcode>
-->


    <opcode id="1f5e" name="OP_SendLoginInfo" updated="02/21/06">
        <comment>Client starting world session by asking for login information</comment>
    </opcode>
    <opcode id="779a" name="OP_GuildList" updated="02/21/06">
        <comment>old GuildListCode</comment>
        <payload dir="server" typename="worldGuildListStruct" sizechecktype="match"/>
    </opcode>
    <opcode id="6bd5" name="OP_LogServer" updated="02/21/06">
        <comment></comment>
    </opcode>
    <opcode id="42c2" name="OP_ApproveWorld" updated="02/21/06">
        <comment></comment>
    </opcode>
    <opcode id="1151" name="OP_EnterWorld" updated="02/21/06">
        <comment>Server approval for client to enter world</comment>
    </opcode>
    <opcode id="04ec" name="OP_ExpansionInfo" updated="12/07/05">
        <comment>Which expansions user has</comment>
    </opcode>
    <opcode id="6526" name="OP_SendCharInfo" updated="02/21/06">
        <comment>Send all chars visible @ char select</comment>
    </opcode>
    <opcode id="207c" name="OP_World_Client_CRC1" updated="02/21/06">
        <comment>Contains a snippet of spell data</comment>
    </opcode>
    <opcode id="5894" name="OP_World_Client_CRC2" updated="02/21/06">
        <comment>Second client verification packet</comment>
    </opcode>
    <opcode id="275e" name="OP_MOTD" updated="02/21/06">
        <comment>old MOTDCode Server message of the day</comment>
        <payload dir="server" typename="worldMOTDStruct" sizechecktype="none"/>
    </opcode>
    <opcode id="1e34" name="OP_SetChatServer" updated="02/21/06">
        <comment>Chatserver? IP,Port,servername.Charname,password(?)</comment>
    </opcode>
    <opcode id="452d" name="OP_SetChatServer2" updated="02/21/06">
        <comment>Chatserver? IP,Port,servername.Charname,password(?)</comment>
    </opcode>
    <opcode id="7ca3" name="OP_ZoneServerInfo" updated="02/21/06">
        <comment>old ZoneServerInfo</comment>
    </opcode>
    <opcode id="3fe1" name="OP_WorldComplete" updated="02/21/06">
        <comment>Client telling world server it is done. World replies by disconnecting.</comment>
    </opcode>


    

    <opcode id="26c9" name="OP_DeleteCharacter" updated="10/27/05">
        <comment>Delete character @ char select</comment>
    </opcode>
    <opcode id="6160" name="OP_CharacterCreate" updated="06/29/04">
        <comment>Create character @ char select</comment>
    </opcode>
    <opcode id="3ea6" name="OP_ApproveName" updated="10/27/04">
        <comment>Approving new character name @ char creation</comment>
    </opcode>
    <opcode id="23d4" name="OP_RandomNameGenerator" updated="06/29/05">
        <comment>Returns a random name</comment>
    </opcode>
</seqopcodes>

=== ShowEQ/ShowEQ/showeq/tags/v5_0_beta5/conf/worldopcodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seqopcodes SYSTEM "seqopcodes.dtd">
<seqopcodes>
    <opcode id="0018" name="OP_AckPacket" updated="02/10/04">
        <comment>Appears to be generic ack at the presentation level</comment>
    </opcode>
    <opcode id="005e" name="OP_GuildList" updated="02/10/04">
        <comment>old GuildListCode</comment>
        <payload dir="server" typename="worldGuildListStruct" sizechecktype="match"/>
    </opcode>
    <opcode id="00e3" name="OP_ExpansionInfo" updated="02/10/04">
        <comment>Which expansions user has</comment>
    </opcode>
    <opcode id="00ec" name="OP_DeleteCharacter" updated="02/10/04">
        <comment>Delete character @ char select</comment>
    </opcode>
    <opcode id="0104" name="OP_SendCharInfo" updated="02/10/04">
        <comment>Send all chars visible @ char select</comment>
    </opcode>
    <opcode id="0106" name="OP_CharacterCreate" updated="02/10/04">
        <comment>Create character @ char select</comment>
    </opcode>
    <opcode id="0127" name="OP_ApproveName" updated="02/10/04">
        <comment>Approving new character name @ char creation</comment>
    </opcode>
    <opcode id="015c" name="OP_World_Client_CRC1" updated="02/10/04">
        <comment>Contains a snippet of spell data</comment>
    </opcode>
    <opcode id="0160" name="OP_World_Client_CRC2" updated="02/10/04">
        <comment>Second client verification packet</comment>
    </opcode>
    <opcode id="0188" name="OP_LogServer" updated="02/10/04">
        <comment></comment>
    </opcode>
    <opcode id="0196" name="OP_ApproveWorld" updated="02/10/04">
        <comment></comment>
    </opcode>
    <opcode id="01b3" name="OP_MOTD" updated="02/10/04">
        <comment>old MOTDCode Server message of the day</comment>
        <payload dir="server" typename="worldMOTDStruct" sizechecktype="none"/>
    </opcode>
    <opcode id="0241" name="OP_SendLoginInfo" updated="02/10/04">
        <comment></comment>
    </opcode>
    <opcode id="0264" name="OP_EnterWorld" updated="02/10/04">
        <comment>Server approval for client to enter world</comment>
    </opcode>
    <opcode id="0267" name="OP_ZoneServerInfo" updated="02/10/04">
        <comment>old ZoneServerInfo</comment>
    </opcode>
    <opcode id="026c" name="OP_SetChatServer" updated="02/10/04">
        <comment>Chatserver? IP,Port,servername.Charname,password(?)</comment>
    </opcode>
    <opcode id="029b" name="OP_GetName" updated="02/10/04">
        <comment>Returns a random name</comment>
    </opcode>
</seqopcodes>
